[env:d_grape]
platform  = ststm32
board     = disco_f407vg
framework = stm32cube

upload_protocol = stlink
debug_tool      = stlink

board_build.f_cpu = 168000000L

extra_scripts = pre:extra_scripts.py

lib_extra_dirs = lib

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F407xx
    "-DCMSIS_device_header=\"stm32f4xx.h\""
    -std=gnu11
    -Iinclude
    -Ilib/motors
    -Ilib/encoders
    -Ilib/pid
    -Ilib/imu
    -Ilib/kalman
    -Ilib/freertos/include
    -Ilib/freertos/portable/GCC/ARM_CM4F
    -Ilib/freertos/CMSIS_RTOS_V2
    -I${platformio.packages_dir}/framework-stm32cubef4/Drivers/CMSIS/Include
    -Os
    -ffunction-sections
    -fdata-sections
    -DMICRO_ROS_TRANSPORT_USB_CDC
    -I lib/micro_ros_platformio/libmicroros/include
    -I lib/usb_cdc
    
lib_ignore =
    AUDIO
    CCID
    CDC_ECM
    CDC_RNDIS
    CustomHID
    DFU
    MSC
    MTP
    Printer
